version: '3.9'

services:
  app:
    build: .
    container_name: chat-app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: chat-app-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: